Antivaly/Controllers/DeliveryManController.cs
using Antivaly.Authentication;
using Antivaly.BusinessModel;
using Antivaly.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Antivaly.Controllers
{
    [DeliveryManAccess]
    public class DeliveryManController : Controller
    {
        // GET: DeliveryMan
        public ActionResult Dashboard()
        {
            var db = new AntivalyEntities();
            var bind = new DeliveryManBind();
            string UID = Session["UID"].ToString();
            TransactionBind bindTransaction = new TransactionBind();

            var t = (from i in db.Transactions
                     where i.Status == "In Processing" && (i.DMID == null || i.DMID == UID) 
                     select i).ToList();

            bindTransaction.Transactions = t;
            bindTransaction.MapData();
            bind.Processing = bindTransaction;

            t = (from i in db.Transactions
                 where i.Status == "Delivered" && i.DMID == UID
                 select i).ToList();

            bindTransaction = new TransactionBind();
            bindTransaction.Transactions = t;
            bindTransaction.MapData();
            bind.Delivered = bindTransaction;


            var user = (from i in db.Deliveries
                        where i.UID == UID
                        select i).FirstOrDefault();
            bind.UserInfo = user;
            bind.Rate();
            var x = bind.IncreasingRate;

            return View(bind);
        }

        public ActionResult Active(int id)
        {
            var db = new AntivalyEntities();
            var update = (from i in db.Transactions
                          where i.TID == id
                          select i).FirstOrDefault();
            update.DMID = Session["UID"].ToString();
            db.SaveChanges();

            var updateDM = (from i in db.Deliveries
                            where i.UID == update.DMID
                            select i).FirstOrDefault();
            updateDM.Status = "Busy";
            db.SaveChanges();

            return RedirectToAction("Dashboard");
        }

        public ActionResult Delivered(int id)
        {
            var db = new AntivalyEntities();
            var update = (from i in db.Transactions
                          where i.TID == id
                          select i).FirstOrDefault();
            update.DMID = Session["UID"].ToString();
            update.Status = "Delivered";
            db.SaveChanges();

            var updateDM = (from i in db.Deliveries
                      where i.UID == update.DMID
                      select i).FirstOrDefault();
            updateDM.Status = "Free";
            updateDM.NumOfOrders++;
            if (updateDM.NumOfOrders % 5 == 0)
                updateDM.DeliveryCharge += 2;
            updateDM.Balance += updateDM.DeliveryCharge;
            db.SaveChanges();

            return RedirectToAction("Dashboard");
        }

        public ActionResult UProfile()
        {
            if (Session["UID"] != null)
            {
                var UID = Session["UID"].ToString();
                AntivalyEntities db = new AntivalyEntities();
                var data = db.Users.FirstOrDefault(u => u.UID == UID);
                ViewBag.UserDetails = data;
                return View();
            }
            return RedirectToAction("Index", "Home");

        }

        public ActionResult EditProfile()
        {
            if (Session["UID"] != null)
            {
                var UID = Session["UID"].ToString();
                AntivalyEntities db = new AntivalyEntities();
                var data = db.Users.FirstOrDefault(u => u.UID == UID);
                ViewBag.UserDetails = data;
                return View();
            }
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public ActionResult EditProfile(EditProfile user)
        {
            if (ModelState.IsValid)
            {
                var db = new AntivalyEntities();
                var User = db.Users.Where(x => x.UID == user.UID).FirstOrDefault();
                if (User != null)
                {
                    User.Name = user.Name;
                    User.Email = user.Email;
                    User.Address = user.Address;
                    User.Contact = user.Contact;
                    db.Entry(User).State = EntityState.Modified;
                    db.SaveChanges();
                }
            }
            return RedirectToAction("UProfile");
        }

        public ActionResult Cancel(int id)
        {
            var db = new AntivalyEntities();
            var update = (from i in db.Transactions
                          where i.TID == id
                          select i).FirstOrDefault();

            var updateDM = (from i in db.Deliveries
                            where i.UID == update.DMID
                            select i).FirstOrDefault();
            updateDM.Status = "Free";
            update.DMID = null;

            db.SaveChanges();

            return RedirectToAction("Dashboard");
        }

    }
}

Antivaly/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
    <style>
        .alert {
            position: fixed;
            display: none;
            padding: 20px;
            background-color: #f44336;
            color: white;
            max-width: 350px;
            width: 50%;
            opacity: 1;
            transition: opacity .6s;
            margin: -50px auto;
            left: 0;
            right: 0;
            border-radius: 15px;
        }

        .closebtn {
            margin-left: 15px;
            color: white;
            font-weight: bold;
            float: right;
            font-size: 22px;
            line-height: 20px;
            cursor: pointer;
            transition: 0.3s;
        }

            .closebtn:hover {
                color: black;
            }
    </style>
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body onload="check()">
    @if (Session["UID"] == null)
    {

        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Antivaly", "About", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <center><p>&copy; @DateTime.Now.Year - Antivaly</p></center>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)

    }
    else if (Session["AccType"].ToString() == "Admin")
    {

        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Antivaly", "About", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Dashboard", "Dashboard", "Admin")</li>
                        <li>@Html.ActionLink("Profile", "UProfile", "Admin")</li>
                        <li>@Html.ActionLink("Control Panel", "Panel", "Admin")</li>
                        <li>@Html.ActionLink("Logout", "Logout", "Home")</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <center><p>&copy; @DateTime.Now.Year - Antivaly</p></center>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)

    }

    else if (Session["AccType"].ToString() == "Buyer")
    {

        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Antivaly", "About", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Dashboard", "Home", "Buyer")</li>
                        <li>@Html.ActionLink("My Cart", "Cart", "Buyer")</li>
                        <li>@Html.ActionLink("Order History", "OrderHistory", "Buyer")</li>
                        <li>@Html.ActionLink("Profile", "UProfile", "Buyer")</li>
                        <li>@Html.ActionLink("Logout", "Logout", "Buyer")</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <center><p>&copy; @DateTime.Now.Year - Antivaly</p></center>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)

    }

    else if (Session["AccType"].ToString() == "Seller")
    {

        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Antivaly", "About", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Dashboard", "Dashboard", "Seller")</li>
                        <li>@Html.ActionLink("Post Product", "PostProduct", "Seller")</li>
                        <li>@Html.ActionLink("Profile", "UProfile", "Seller")</li>
                        <li>@Html.ActionLink("Logout", "Logout", "Home")</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <center><p>&copy; @DateTime.Now.Year - Antivaly</p></center>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)

    }

    else if (Session["AccType"].ToString() == "Delivery Man")
    {

        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Antivaly", "About", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Dashboard", "Dashboard", "DeliveryMan")</li>
                        <li>@Html.ActionLink("Profile", "UProfile", "DeliveryMan")</li>
                        <li>@Html.ActionLink("Logout", "Logout", "Home")</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <center><p>&copy; @DateTime.Now.Year - Antivaly</p></center>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)

    }
</body>
</html>